### ISSUE TITLE
Merging Ubuntu with js9 returns internal server error

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-hub#27]
**Steps**
- Merge ubuntu image with (js9+ubuntu) flist 

**actual result**
- Internal server error

**expected result**
- it should return flist

**Comment by maxux** [comment]
I keep this issue open, nothing changed, it still need investigation

**Comment by maxux** [comment]
Since lot of merges was made since this problem, without issues, I close it.
If any merge fails again, please re-open it.
