### ISSUE TITLE
Allow promotion of autobuild flist to official

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-hub#31]
It would be nice to have a method to be able to create symlink between different user/group.
My use case is, I have some autobuild script that generate flist for each commit. When I release a version I want to promote a certain build to be in gig-official apps.

**Comment by maxux** [comment]
Fixed by eaa66f61e175861c23869e4b47fb73b3c01ce7ce and 0856f1770152d8008068d4878cfe50c33811bd26

**Comment by zaibon** [comment]
How are we supposed to use this feature from the client ? I didn't see any update for it in these 2 commits

**Comment by maxux** [comment]
True. Nice catch. Still need to implement this.
