### ISSUE TITLE
promote api call return false success

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-hub#33]
I tried to promote an flist from my personal repo to tf-official-apps, the api call returned success, but the flist has not been promoted.

```python
hub = j.clients.zhub.get('tf')
iyo = j.clients.itsyouonline.get('main')

jwt = iyo.jwt_get(scope='user:memberof:gig-official-apps', refreshable=True)

hub = j.clients.zhub.get('tf')
hub.config.data_set('token_', jwt)

hub.username = 'tf-official-apps'
hub.authenticate()
hub.promote('zaibon','ubuntu_bionic','ubuntu-bionic-build.flist')
```

result is ` {'status': 'success'}` but no flist has been promoted

**Comment by maxux** [comment]
The `success` should be fixed, but promote to `tf-official-apps` when not being **memberof** this organization could not works.
